[package]
name = "like_and_subscribe"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
color-eyre = "0.6.5"
facet = "0.28.0"
facet-derive = "0.27.11"
facet-json = "0.28.1"
google-youtube3 = "6.0.0"
hyper-rustls = { version = "0.27.7", features = ["http2"] }
hyper-util = "0.1.16"
reqwest = "0.12.22"
rustls = "0.23.31"
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["full"] }
