[workspace]
resolver = "3"
members  = ["crates/*"]

[workspace.dependencies]
migration = { version = "0.1.0", path = "crates/migration" }
entity    = { version = "0.1.0", path = "crates/entity" }

tokio        = { version = "1.47.0", features = ["full"] }
sea-orm      = { version = "1.1.14", features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"] }
serde        = "1.0.219"
serde_derive = "1.0.219"
