[package]
name    = "like_and_subscribe"
version = "0.1.0"
edition = "2024"

[dependencies]
axum               = "0.8.4"
axum-extra         = { version = "0.10.1", features = ["error-response", "typed-header"] }
color-eyre         = "0.6.5"
google-youtube3    = "6.0.0"
hyper-rustls       = { version = "0.27.7", features = ["http2"] }
hyper-util         = "0.1.16"
jiff               = { version = "0.2.15", features = ["serde"] }
mime               = "0.3.17"
monostate          = "0.1.14"
quick-xml          = { version = "0.38.0", features = ["serialize"] }
reqwest            = { version = "0.12.22", features = ["json"] }
rustls             = "0.23.31"
serde              = "1.0.219"
serde_derive       = "1.0.219"
serde_json         = "1.0.141"
tokio              = { version = "1.47.0", features = ["full"] }
tower              = { version = "0.5.2", features = ["buffer", "limit"] }
tower-http         = { version = "0.6.6", features = ["trace"] }
tracing            = "0.1.41"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
venator = "1.1.0"
