[build]
default-target = "armv7-unknown-linux-gnueabihf"

[build.env]
passthrough = ["BINDGEN_EXTRA_CLANG_ARGS", "BINDGEN_EXTRA_CLANG_ARGS=-I/usr/lib/llvm-8/lib/clang/8.0.0/include"]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "apt update",
    "apt remove --assume-yes libclang1-3.8",
    "apt autoremove --assume-yes",
    "apt install --assume-yes --no-install-recommends clang-8"
]