//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "active_subscriptions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub channel_id: String,
    pub expiration: entity_types::jiff_compat::JiffTimestampMilliseconds,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::known_channels::Entity",
        from = "Column::ChannelId",
        to = "super::known_channels::Column::ChannelId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KnownChannels,
}

impl Related<super::known_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnownChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
