//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "known_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub channel_id: String,
    #[sea_orm(column_type = "Text")]
    pub channel_name: String,
    #[sea_orm(column_type = "Text")]
    pub channel_profile_picture: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::active_subscriptions::Entity")]
    ActiveSubscriptions,
    #[sea_orm(has_many = "super::known_videos::Entity")]
    KnownVideos,
    #[sea_orm(has_many = "super::subscription_queue::Entity")]
    SubscriptionQueue,
    #[sea_orm(has_many = "super::video_queue::Entity")]
    VideoQueue,
}

impl Related<super::active_subscriptions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActiveSubscriptions.def()
    }
}

impl Related<super::known_videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnownVideos.def()
    }
}

impl Related<super::subscription_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubscriptionQueue.def()
    }
}

impl Related<super::video_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VideoQueue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
