//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::{Linked, RelationDef, RelationTrait as _};

pub mod prelude;

pub mod active_subscriptions;
pub mod known_channels;
pub mod o_auth;
pub mod subscription_queue;
pub mod subscription_queue_result;
pub mod video_queue;
pub mod video_queue_result;

pub struct SubscriptionQueueToActiveSubscriptions;

impl Linked for SubscriptionQueueToActiveSubscriptions {
    type FromEntity = subscription_queue::Entity;
    type ToEntity = active_subscriptions::Entity;

    fn link(&self) -> Vec<RelationDef> {
        vec![
            known_channels::Relation::SubscriptionQueue.def().rev(),
            known_channels::Relation::ActiveSubscriptions.def(),
        ]
    }
}
