//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "o_auth")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub row_id: i32,
    #[sea_orm(column_type = "Text")]
    pub access_token: String,
    #[sea_orm(column_type = "Text")]
    pub refresh_token: String,
    pub expires_at: jiff_sea_orm_compat::JiffTimestampMilliseconds,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
