[package]
name         = "entity"
version      = "0.1.0"
edition      = "2024"
rust-version = "1.85.0"
publish      = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
sea-orm             = { workspace = true }
serde               = { workspace = true }
serde_derive        = { workspace = true }
jiff_sea-orm_compat = { workspace = true }
